% ── Area order (cytoarchitectonic hierarchy) ──────────────────────────────
area_order = {
    '24c',                                  ... % MFC
    '6DR',  '6DC',  '6VaVb',               ... % PMC
    '8B',   '8A',   '46d', '46df', '46v',  ... % dlPFC
    '44',   '45',                           ... % IFG
    '12r',  '12m',  '12o', '12l',          ... % vlPFC
    'AI',                                   ... % agranular insula
    '13l',  '13m',  '11ml',                ... % OFC
    'cd',   'pu',                           ... % striatum
    'AMG'};                                     % amygdala

% ── Region colour map (one row per region) ────────────────────────────────
region_colours = [
    0.6  0.2  0.6;   % MFC      - purple
    0.9  0.5  0.1;   % PMC      - orange
    0.2  0.6  0.9;   % dlPFC    - blue
    0.3  0.7  0.4;   % IFG      - green
    0.1  0.4  0.7;   % vlPFC    - dark blue
    0.7  0.7  0.3;   % AI       - yellow
    0.8  0.3  0.3;   % OFC      - red
    0.5  0.5  0.5;   % striatum - grey
    0.3  0.3  0.3];  % amygdala - dark grey

% ── Region map: one integer per area, indexing into region_colours ────────
region_map = [...
    1, ...          % 24c        MFC
    2, 2, 2, ...    % 6DR 6DC 6VaVb   PMC
    3, 3, 3, 3, 3, ... % 8B 8A 46d 46df 46v  dlPFC
    4, 4, ...       % 44 45      IFG
    5, 5, 5, 5, ... % 12r 12m 12o 12l  vlPFC
    6, ...          % AI
    7, 7, 7, ...    % 13l 13m 11ml     OFC
    8, 8, ...       % cd pu      striatum
    9];             % AMG

%% ========================================================================
% plot_population_sdfs.m
% Example calls to plot_area_sdfs for each aligned SDF array.
% Assumes the following variables are in the workspace:
%   z_fixation_array  : nNeurons x nTime x 4  (stim_on aligned, foreperiod split)
%   z_decision_array  : nNeurons x nTime x nConds
%   z_reward_array    : nNeurons x nTime x nConds
%   analysis_log      : table with 'area', 'ramping_fp_flag'
%   area_order        : cell array of area names in hierarchy order
%   region_colours    : nRegions x 3 RGB
%   region_map        : 1 x nAreas int, maps each area to region_colours row
%   dirs.figures      : path to figures directory
% =========================================================================

% ── Shared layout ─────────────────────────────────────────────────────────
% Condition colours: light → dark blue for foreperiod conditions
fp_colors = [
    0.36 0.76 0.94;   % short  — light blue
    0.10 0.40 0.70;   % medium — mid blue
    0.00 0.17 0.43;   % long   — dark blue
];

% Standard time vector for all arrays (-2000 to 2000 ms)
time_vec = -2000:2000;

% ── 1. Foreperiod-split SDF (stim_on aligned) ─────────────────────────────
% z_fixation_array dim 3: 1=all, 2=short, 3=medium, 4=long
% Plot short/medium/long only (skip 'all')

plot_area_sdfs(z_fixation_array, time_vec, analysis_log, ...
    area_order, region_colours, ...
    'ConditionLabels', {'Short', 'Medium', 'Long'}, ...
    'ConditionColors', fp_colors, ...
    'ConditionIdx',    [2, 3, 4], ...
    'XLim',            [-1500 250], ...
    'VLines',          [-1300 -1000 -700 0], ...
    'VLineStyle',      '--', ...
    'PlotSEM',         true, ...
    'MinN',            5, ...
    'NCols',           4, ...
    'FigureTitle',     'Foreperiod SDF (stim on)', ...
    'RegionMap',       region_map, ...
    'SavePath',        fullfile(dirs.figures, 'foreperiod_sdf'));


% ── 2. Decision-aligned SDF ───────────────────────────────────────────────
% Adjust ConditionLabels / ConditionIdx / XLim to match your array structure

% Example: 2 conditions (e.g. chosen left vs chosen right)
decision_colors = [
    0.00 0.00 0.00;
    0.20 0.63 0.17;   % condition 1 — green
    0.84 0.15 0.16;   % condition 2 — red
];

plot_area_sdfs(z_decision_array, time_vec, analysis_log, ...
    area_order, region_colours, ...
    'ConditionLabels', {'All', 'Left', 'Right'}, ...
    'ConditionColors', decision_colors, ...
    'ConditionIdx',    [2 3], ...
    'XLim',            [-500 1000], ...
    'VLines',          [0], ...
    'VLineStyle',      'k-', ...
    'PlotSEM',         true, ...
    'MinN',            5, ...
    'NCols',           4, ...
    'FigureTitle',     'Decision SDF', ...
    'RegionMap',       region_map, ...
    'SavePath',        fullfile(dirs.figures, 'decision_sdf'));


% ── 3. Reward-aligned SDF ─────────────────────────────────────────────────
% Example: 2 conditions (rewarded vs unrewarded)
reward_colors = [
    0.12 0.47 0.71;   % rewarded     — blue
    0.50 0.50 0.50;   % unrewarded   — grey
];

plot_area_sdfs(z_reward_array, time_vec, analysis_log, ...
    area_order, region_colours, ...
    'ConditionLabels', {'Rewarded', 'Unrewarded'}, ...
    'ConditionColors', reward_colors, ...
    'ConditionIdx',    [1], ...
    'XLim',            [-500 1000], ...
    'VLines',          [0], ...
    'VLineStyle',      'k-', ...
    'PlotSEM',         true, ...
    'MinN',            5, ...
    'NCols',           4, ...
    'FigureTitle',     'Reward SDF', ...
    'RegionMap',       region_map, ...
    'SavePath',        fullfile(dirs.figures, 'reward_sdf'));